/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ApiPublicIngestRouteImport } from './routes/api/public/ingest'
import { Route as ApiPublicHeartbeatRouteImport } from './routes/api/public/heartbeat'
import { Route as AuthenticatedAppWebhooksRouteImport } from './routes/_authenticated/app/webhooks'
import { Route as AuthenticatedAppTransfersRouteImport } from './routes/_authenticated/app/transfers'
import { Route as AuthenticatedAppTransactionsRouteImport } from './routes/_authenticated/app/transactions'
import { Route as AuthenticatedAppTeamRouteImport } from './routes/_authenticated/app/team'
import { Route as AuthenticatedAppSourcesRouteImport } from './routes/_authenticated/app/sources'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app/settings'
import { Route as AuthenticatedAppRiskRouteImport } from './routes/_authenticated/app/risk'
import { Route as AuthenticatedAppOrdersRouteImport } from './routes/_authenticated/app/orders'
import { Route as AuthenticatedAppIntegrationsRouteImport } from './routes/_authenticated/app/integrations'
import { Route as AuthenticatedAppConfirmationsRouteImport } from './routes/_authenticated/app/confirmations'
import { Route as AuthenticatedAppBalancesRouteImport } from './routes/_authenticated/app/balances'
import { Route as AuthenticatedAppApiKeysRouteImport } from './routes/_authenticated/app/api-keys'
import { Route as AuthenticatedAppAlertsRouteImport } from './routes/_authenticated/app/alerts'
import { Route as AuthenticatedAdminSystemRouteImport } from './routes/_authenticated/admin/system'
import { Route as AuthenticatedAdminParserRouteImport } from './routes/_authenticated/admin/parser'
import { Route as AuthenticatedAdminMerchantsRouteImport } from './routes/_authenticated/admin/merchants'
import { Route as AuthenticatedAdminFraudRouteImport } from './routes/_authenticated/admin/fraud'
import { Route as AuthenticatedAdminDevicesRouteImport } from './routes/_authenticated/admin/devices'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicIngestRoute = ApiPublicIngestRouteImport.update({
  id: '/api/public/ingest',
  path: '/api/public/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHeartbeatRoute = ApiPublicHeartbeatRouteImport.update({
  id: '/api/public/heartbeat',
  path: '/api/public/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppWebhooksRoute =
  AuthenticatedAppWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTransfersRoute =
  AuthenticatedAppTransfersRouteImport.update({
    id: '/transfers',
    path: '/transfers',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTransactionsRoute =
  AuthenticatedAppTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTeamRoute = AuthenticatedAppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSourcesRoute = AuthenticatedAppSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppRiskRoute = AuthenticatedAppRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppOrdersRoute = AuthenticatedAppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppIntegrationsRoute =
  AuthenticatedAppIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppConfirmationsRoute =
  AuthenticatedAppConfirmationsRouteImport.update({
    id: '/confirmations',
    path: '/confirmations',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBalancesRoute =
  AuthenticatedAppBalancesRouteImport.update({
    id: '/balances',
    path: '/balances',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppApiKeysRoute = AuthenticatedAppApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAlertsRoute = AuthenticatedAppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAdminSystemRoute =
  AuthenticatedAdminSystemRouteImport.update({
    id: '/system',
    path: '/system',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminParserRoute =
  AuthenticatedAdminParserRouteImport.update({
    id: '/parser',
    path: '/parser',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMerchantsRoute =
  AuthenticatedAdminMerchantsRouteImport.update({
    id: '/merchants',
    path: '/merchants',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFraudRoute = AuthenticatedAdminFraudRouteImport.update({
  id: '/fraud',
  path: '/fraud',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminDevicesRoute =
  AuthenticatedAdminDevicesRouteImport.update({
    id: '/devices',
    path: '/devices',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/admin/devices': typeof AuthenticatedAdminDevicesRoute
  '/admin/fraud': typeof AuthenticatedAdminFraudRoute
  '/admin/merchants': typeof AuthenticatedAdminMerchantsRoute
  '/admin/parser': typeof AuthenticatedAdminParserRoute
  '/admin/system': typeof AuthenticatedAdminSystemRoute
  '/app/alerts': typeof AuthenticatedAppAlertsRoute
  '/app/api-keys': typeof AuthenticatedAppApiKeysRoute
  '/app/balances': typeof AuthenticatedAppBalancesRoute
  '/app/confirmations': typeof AuthenticatedAppConfirmationsRoute
  '/app/integrations': typeof AuthenticatedAppIntegrationsRoute
  '/app/orders': typeof AuthenticatedAppOrdersRoute
  '/app/risk': typeof AuthenticatedAppRiskRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/sources': typeof AuthenticatedAppSourcesRoute
  '/app/team': typeof AuthenticatedAppTeamRoute
  '/app/transactions': typeof AuthenticatedAppTransactionsRoute
  '/app/transfers': typeof AuthenticatedAppTransfersRoute
  '/app/webhooks': typeof AuthenticatedAppWebhooksRoute
  '/api/public/heartbeat': typeof ApiPublicHeartbeatRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/devices': typeof AuthenticatedAdminDevicesRoute
  '/admin/fraud': typeof AuthenticatedAdminFraudRoute
  '/admin/merchants': typeof AuthenticatedAdminMerchantsRoute
  '/admin/parser': typeof AuthenticatedAdminParserRoute
  '/admin/system': typeof AuthenticatedAdminSystemRoute
  '/app/alerts': typeof AuthenticatedAppAlertsRoute
  '/app/api-keys': typeof AuthenticatedAppApiKeysRoute
  '/app/balances': typeof AuthenticatedAppBalancesRoute
  '/app/confirmations': typeof AuthenticatedAppConfirmationsRoute
  '/app/integrations': typeof AuthenticatedAppIntegrationsRoute
  '/app/orders': typeof AuthenticatedAppOrdersRoute
  '/app/risk': typeof AuthenticatedAppRiskRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/sources': typeof AuthenticatedAppSourcesRoute
  '/app/team': typeof AuthenticatedAppTeamRoute
  '/app/transactions': typeof AuthenticatedAppTransactionsRoute
  '/app/transfers': typeof AuthenticatedAppTransfersRoute
  '/app/webhooks': typeof AuthenticatedAppWebhooksRoute
  '/api/public/heartbeat': typeof ApiPublicHeartbeatRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/admin/devices': typeof AuthenticatedAdminDevicesRoute
  '/_authenticated/admin/fraud': typeof AuthenticatedAdminFraudRoute
  '/_authenticated/admin/merchants': typeof AuthenticatedAdminMerchantsRoute
  '/_authenticated/admin/parser': typeof AuthenticatedAdminParserRoute
  '/_authenticated/admin/system': typeof AuthenticatedAdminSystemRoute
  '/_authenticated/app/alerts': typeof AuthenticatedAppAlertsRoute
  '/_authenticated/app/api-keys': typeof AuthenticatedAppApiKeysRoute
  '/_authenticated/app/balances': typeof AuthenticatedAppBalancesRoute
  '/_authenticated/app/confirmations': typeof AuthenticatedAppConfirmationsRoute
  '/_authenticated/app/integrations': typeof AuthenticatedAppIntegrationsRoute
  '/_authenticated/app/orders': typeof AuthenticatedAppOrdersRoute
  '/_authenticated/app/risk': typeof AuthenticatedAppRiskRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/sources': typeof AuthenticatedAppSourcesRoute
  '/_authenticated/app/team': typeof AuthenticatedAppTeamRoute
  '/_authenticated/app/transactions': typeof AuthenticatedAppTransactionsRoute
  '/_authenticated/app/transfers': typeof AuthenticatedAppTransfersRoute
  '/_authenticated/app/webhooks': typeof AuthenticatedAppWebhooksRoute
  '/api/public/heartbeat': typeof ApiPublicHeartbeatRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/app'
    | '/admin/devices'
    | '/admin/fraud'
    | '/admin/merchants'
    | '/admin/parser'
    | '/admin/system'
    | '/app/alerts'
    | '/app/api-keys'
    | '/app/balances'
    | '/app/confirmations'
    | '/app/integrations'
    | '/app/orders'
    | '/app/risk'
    | '/app/settings'
    | '/app/sources'
    | '/app/team'
    | '/app/transactions'
    | '/app/transfers'
    | '/app/webhooks'
    | '/api/public/heartbeat'
    | '/api/public/ingest'
    | '/admin/'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin/devices'
    | '/admin/fraud'
    | '/admin/merchants'
    | '/admin/parser'
    | '/admin/system'
    | '/app/alerts'
    | '/app/api-keys'
    | '/app/balances'
    | '/app/confirmations'
    | '/app/integrations'
    | '/app/orders'
    | '/app/risk'
    | '/app/settings'
    | '/app/sources'
    | '/app/team'
    | '/app/transactions'
    | '/app/transfers'
    | '/app/webhooks'
    | '/api/public/heartbeat'
    | '/api/public/ingest'
    | '/admin'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/admin/devices'
    | '/_authenticated/admin/fraud'
    | '/_authenticated/admin/merchants'
    | '/_authenticated/admin/parser'
    | '/_authenticated/admin/system'
    | '/_authenticated/app/alerts'
    | '/_authenticated/app/api-keys'
    | '/_authenticated/app/balances'
    | '/_authenticated/app/confirmations'
    | '/_authenticated/app/integrations'
    | '/_authenticated/app/orders'
    | '/_authenticated/app/risk'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/sources'
    | '/_authenticated/app/team'
    | '/_authenticated/app/transactions'
    | '/_authenticated/app/transfers'
    | '/_authenticated/app/webhooks'
    | '/api/public/heartbeat'
    | '/api/public/ingest'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiPublicHeartbeatRoute: typeof ApiPublicHeartbeatRoute
  ApiPublicIngestRoute: typeof ApiPublicIngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/ingest': {
      id: '/api/public/ingest'
      path: '/api/public/ingest'
      fullPath: '/api/public/ingest'
      preLoaderRoute: typeof ApiPublicIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/heartbeat': {
      id: '/api/public/heartbeat'
      path: '/api/public/heartbeat'
      fullPath: '/api/public/heartbeat'
      preLoaderRoute: typeof ApiPublicHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/webhooks': {
      id: '/_authenticated/app/webhooks'
      path: '/webhooks'
      fullPath: '/app/webhooks'
      preLoaderRoute: typeof AuthenticatedAppWebhooksRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/transfers': {
      id: '/_authenticated/app/transfers'
      path: '/transfers'
      fullPath: '/app/transfers'
      preLoaderRoute: typeof AuthenticatedAppTransfersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/transactions': {
      id: '/_authenticated/app/transactions'
      path: '/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AuthenticatedAppTransactionsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/team': {
      id: '/_authenticated/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AuthenticatedAppTeamRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/sources': {
      id: '/_authenticated/app/sources'
      path: '/sources'
      fullPath: '/app/sources'
      preLoaderRoute: typeof AuthenticatedAppSourcesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/risk': {
      id: '/_authenticated/app/risk'
      path: '/risk'
      fullPath: '/app/risk'
      preLoaderRoute: typeof AuthenticatedAppRiskRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/orders': {
      id: '/_authenticated/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AuthenticatedAppOrdersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/integrations': {
      id: '/_authenticated/app/integrations'
      path: '/integrations'
      fullPath: '/app/integrations'
      preLoaderRoute: typeof AuthenticatedAppIntegrationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/confirmations': {
      id: '/_authenticated/app/confirmations'
      path: '/confirmations'
      fullPath: '/app/confirmations'
      preLoaderRoute: typeof AuthenticatedAppConfirmationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/balances': {
      id: '/_authenticated/app/balances'
      path: '/balances'
      fullPath: '/app/balances'
      preLoaderRoute: typeof AuthenticatedAppBalancesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/api-keys': {
      id: '/_authenticated/app/api-keys'
      path: '/api-keys'
      fullPath: '/app/api-keys'
      preLoaderRoute: typeof AuthenticatedAppApiKeysRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/alerts': {
      id: '/_authenticated/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AuthenticatedAppAlertsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/system': {
      id: '/_authenticated/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AuthenticatedAdminSystemRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/parser': {
      id: '/_authenticated/admin/parser'
      path: '/parser'
      fullPath: '/admin/parser'
      preLoaderRoute: typeof AuthenticatedAdminParserRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/merchants': {
      id: '/_authenticated/admin/merchants'
      path: '/merchants'
      fullPath: '/admin/merchants'
      preLoaderRoute: typeof AuthenticatedAdminMerchantsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/fraud': {
      id: '/_authenticated/admin/fraud'
      path: '/fraud'
      fullPath: '/admin/fraud'
      preLoaderRoute: typeof AuthenticatedAdminFraudRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/devices': {
      id: '/_authenticated/admin/devices'
      path: '/devices'
      fullPath: '/admin/devices'
      preLoaderRoute: typeof AuthenticatedAdminDevicesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminDevicesRoute: typeof AuthenticatedAdminDevicesRoute
  AuthenticatedAdminFraudRoute: typeof AuthenticatedAdminFraudRoute
  AuthenticatedAdminMerchantsRoute: typeof AuthenticatedAdminMerchantsRoute
  AuthenticatedAdminParserRoute: typeof AuthenticatedAdminParserRoute
  AuthenticatedAdminSystemRoute: typeof AuthenticatedAdminSystemRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminDevicesRoute: AuthenticatedAdminDevicesRoute,
  AuthenticatedAdminFraudRoute: AuthenticatedAdminFraudRoute,
  AuthenticatedAdminMerchantsRoute: AuthenticatedAdminMerchantsRoute,
  AuthenticatedAdminParserRoute: AuthenticatedAdminParserRoute,
  AuthenticatedAdminSystemRoute: AuthenticatedAdminSystemRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAlertsRoute: typeof AuthenticatedAppAlertsRoute
  AuthenticatedAppApiKeysRoute: typeof AuthenticatedAppApiKeysRoute
  AuthenticatedAppBalancesRoute: typeof AuthenticatedAppBalancesRoute
  AuthenticatedAppConfirmationsRoute: typeof AuthenticatedAppConfirmationsRoute
  AuthenticatedAppIntegrationsRoute: typeof AuthenticatedAppIntegrationsRoute
  AuthenticatedAppOrdersRoute: typeof AuthenticatedAppOrdersRoute
  AuthenticatedAppRiskRoute: typeof AuthenticatedAppRiskRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppSourcesRoute: typeof AuthenticatedAppSourcesRoute
  AuthenticatedAppTeamRoute: typeof AuthenticatedAppTeamRoute
  AuthenticatedAppTransactionsRoute: typeof AuthenticatedAppTransactionsRoute
  AuthenticatedAppTransfersRoute: typeof AuthenticatedAppTransfersRoute
  AuthenticatedAppWebhooksRoute: typeof AuthenticatedAppWebhooksRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAlertsRoute: AuthenticatedAppAlertsRoute,
  AuthenticatedAppApiKeysRoute: AuthenticatedAppApiKeysRoute,
  AuthenticatedAppBalancesRoute: AuthenticatedAppBalancesRoute,
  AuthenticatedAppConfirmationsRoute: AuthenticatedAppConfirmationsRoute,
  AuthenticatedAppIntegrationsRoute: AuthenticatedAppIntegrationsRoute,
  AuthenticatedAppOrdersRoute: AuthenticatedAppOrdersRoute,
  AuthenticatedAppRiskRoute: AuthenticatedAppRiskRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppSourcesRoute: AuthenticatedAppSourcesRoute,
  AuthenticatedAppTeamRoute: AuthenticatedAppTeamRoute,
  AuthenticatedAppTransactionsRoute: AuthenticatedAppTransactionsRoute,
  AuthenticatedAppTransfersRoute: AuthenticatedAppTransfersRoute,
  AuthenticatedAppWebhooksRoute: AuthenticatedAppWebhooksRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiPublicHeartbeatRoute: ApiPublicHeartbeatRoute,
  ApiPublicIngestRoute: ApiPublicIngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
